---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
data:
  password: cGFzc3dvcmQxMjM= # Base64-encoded password123
  username: YWRtaW51c2Vy # Base64-encoded adminuser

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: cloudasst2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi # Adjust as needed

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudasst2-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudasst2-flask
      version: v1
  template:
    metadata:
      labels:
        app: cloudasst2-flask
        version: v1
    spec:
      containers:
        - name: flask-app
          image: aravindkrish23/cloudasst2:alpha
          ports:
            - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudasst2-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudasst2-db
      version: v1
  template:
    metadata:
      labels:
        app: cloudasst2-db
        version: v1
    spec:
      containers:
        - name: db-app
          image: aravindkrish23/cloudasst2:alpha_db
          ports:
            - containerPort: 27017          
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db # Adjust as needed
          resources:
            limits:
              cpu: "0.5"
              memory: "128Mi"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: cloudasst2-flask-lb
  namespace: cloudasst2
spec:
  selector:
    app: cloudasst2-flask
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: cloudasst2-db-lb
  namespace: cloudasst2
spec:
  selector:
    app: cloudasst2-db
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer





