  version: '3'
  services:
    flask-api:
      build: .
      ports:
        - "5000:5000"
      environment:
        - MONGO_HOST=mongodb
        - MONGO_PORT=27017
      depends_on:
        - mongodb

    mongodb:
      image: mongo
      volumes:
        - mongo-data:/data/db 

  volumes:
    mongo-data: