  version: '3'
  services:
    mongo:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db 
    flask-api:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5000:5000"

  volumes:
    mongo-data: